title: Product input
type: object
properties:
  name:
    type: string
  description:
    type: string
  available_on:
    type: string
  permalink:
    type: string
  meta_description:
    type: string
  meta_keywords:
    type: string
  price:
    type: string
  sku:
    type: string
  deleted_at:
    type: string
  option_values_hash:
    type: object
  weight:
    type: string
  height:
    type: string
  width:
    type: string
  depth:
    type: string
  shipping_category_id:
    type: integer
  tax_category_id:
    type: integer
  taxon_ids:
    type: array
    items:
      type: integer
  option_type_ids:
    type: array
    items:
      type: integer
  cost_currency:
    type: string
  cost_price:
    type: string
  product_properties_attributes:
    type: array
    items:
      $ref: './product-property-input.v1.yaml'
